/*
 * GPS Navigation ---An open source GPS navigation core software
 *
 *
 * Copyright (c) 2016  Hitachi, Ltd.
 *
 * This program is dual licensed under GPL version 2 or a commercial license.
 * See the LICENSE file distributed with this source file.
 */

#ifndef SMCCOMCMNINTERNAL_H_
#define SMCCOMCMNINTERNAL_H_

#include "sms-core/internal/smsstd.h"
#include "sms-core/internal/smstypedef.h"
#include "sms-core/internal/smsutil.h"
#include "sms-core/internal/smscore.h"
#include "sms-core/internal/smscorecmn.h"
#include "sms-core/internal/smscal.h"
#include "sms-core/internal/smsccomcmn.h"
#include "sms-core/internal/smsccomdal.h"

#ifdef __SMS_APPLE__
#include <sys/mount.h>
#endif /* __SMS_APPLE__ */

#include "SMCComAWS.h"
#include "SMCComDL.h"

#include "SMCComAgreeauthReq.h"
#include "SMCComAppconfReg.h"
#include "SMCComAppconfReq.h"
#include "SMCComAreaInfoList.h"
#include "SMCComAuthReq.h"
#include "SMCComBackup.h"
#include "SMCComChatHis.h"
#include "SMCComChatMsg.h"
#include "SMCComChkMapUpd.h"
#include "SMCComDaialogStatusReq.h"
#include "SMCComDeviceidReq.h"
#include "SMCComDriveCheckListReq.h"
#include "SMCComDriveCheckReq.h"
#include "SMCComGemAlt.h"
#include "SMCComGemCommentAlt.h"
#include "SMCComGemCommentDel.h"
#include "SMCComGemCommentReg.h"
#include "SMCComGemCommentReq.h"
#include "SMCComGemDel.h"
#include "SMCComGemIdSearch.h"
#include "SMCComGemLikeCncl.h"
#include "SMCComGemLikeReg.h"
#include "SMCComGemLikeReq.h"
#include "SMCComGemReg.h"
#include "SMCComGemSearch.h"
#include "SMCComGemspotIdSearch.h"
#include "SMCComGemspotKwdSearch.h"
#include "SMCComGemTimelineSearch.h"
#include "SMCComGroupSearch.h"
#include "SMCComMapdatabktReq.h"
#include "SMCComMappingAlt.h"
#include "SMCComMappingCommentAlt.h"
#include "SMCComMappingCommentDel.h"
#include "SMCComMappingCommentReg.h"
#include "SMCComMappingCommentReq.h"
#include "SMCComMappingDel.h"
#include "SMCComMappingHistoryReq.h"
#include "SMCComMappingIdSrch.h"
#include "SMCComMappingLikeDel.h"
#include "SMCComMappingLikeReg.h"
#include "SMCComMappingLikeReq.h"
#include "SMCComMappingRateReg.h"
#include "SMCComMappingRateReq.h"
#include "SMCComMappingReg.h"
#include "SMCComMappingSrch.h"
#include "SMCComMemberSrch.h"
#include "SMCComMessageInbox.h"
#include "SMCComMessageProcess.h"
#include "SMCComNoticeListReq.h"
#include "SMCComNoticeReq.h"
#include "SMCComNotifyReg.h"
#include "SMCComOAuthUrlReq.h"
#include "SMCComParkingrateReq.h"
#include "SMCComPasswdAlt.h"
#include "SMCComPkgChkTampering.h"
#include "SMCComPkgCodeDel.h"
#include "SMCComPkgCodeReg.h"
#include "SMCComPkgCommon.h"
#include "SMCComPkgLock.h"
#include "SMCComPkgLock.h"
#include "SMCComPkgReq.h"
#include "SMCComPkgWhiteList.h"
#include "SMCComPosInfoSearch.h"
#include "SMCComPosInfoUpdate.h"
#include "SMCComPrjNoReq.h"
#include "SMCComProbepostReq.h"
#include "SMCComProbepostComp.h"
#include "SMCComProbeReq.h"
#include "SMCComRatingReg.h"
#include "SMCComRgnInfoList.h"
#include "SMCComRnameAlt.h"
#include "SMCComRoomReg.h"
#include "SMCComUserSrch.h"
#include "SMCComRoomSrch.h"
#include "SMCComSensorProbepostReq.h"
#include "SMCComStarSrchAlt.h"
#include "SMCComTermReg.h"
#include "SMCComTokenReq.h"
#include "SMCComTrafficInfo.h"
#include "SMCComUnreadSrch.h"
#include "SMCComUpdDataProgressMng.h"
#include "SMCComUpdDataReq.h"
#include "SMCComUser_Srch.h"
#include "SMCComUserattrInfo.h"
#include "SMCComUserpolicyReq.h"
#include "SMCComUserReg.h"

#include "SMCComApi.h"
#include "SMCComCmnCtrl.h"

#endif /* SMCCOMCMNINTERNAL_H_ */
